export default {
  gameLoopStart: 'gameLoopStart'
  , gameLoopContinue: 'gameLoopContinue'
  , gameLoopApply: 'gameLoopApply'
  , gameLoopEnergy: 'gameLoopEnergy'
  , gameLoopStop: 'gameLoopStop'
  , loadGameViewComplete: 'loadGameViewComplete'
  , loadLevelComplete: 'loadLevelComplete'
  , gameSpawnPlayer: 'gameSpawnPlayer'
  , gameEvent: 'gameEvent'
  , entityCommand: 'entityCommand'
  , playerModeChange: 'playerModeChange'
  , playerCursorMove: 'playerCursorMove'
  , playerQueueShift: 'playerQueueShift'
  , playerQueueClear: 'playerQueueClear'

  , entityCommandRequestActions: 'entityCommandRequestActions'
  , entityCommandGetResult: 'entityCommandGetResult'
  , entityCommandApplyEffect: 'entityCommandApplyEffect'
  , entityCommandScheduleEffect: 'entityCommandScheduleEffect'
  , entityCommandApplyEffects: 'entityCommandApplyEffects'
  , entityApplyEffect: 'entityApplyEffect'
};
