export default {
  MOVE: 'MOVE'
  , OPEN: 'OPEN'
  , CLOSE: 'CLOSE'
  , TARGET: 'TARGET'
  , TARGET_CANCEL: 'TARGET_CANCEL'
  , INTERACT: 'INTERACT'
  , COMBINED: 'COMBINED'
  , SWITCH: 'SWITCH'
  , SIGNAL_EMIT: 'SIGNAL_EMIT'
  , SIGNAL_TRAVERSE: 'SIGNAL_TRAVERSE'
  , ENTITY_EFFECT: 'ENTITY_EFFECT'
}